version: "3.11"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data